/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/db/set DETECTOR experiment "ANNIE" 
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan_sandi.geo" 


/run/initialize
#/rat/physics/scintillation/meanPhotonsPerSecondary 1
/rat/proc splitevdaq
/rat/proclast outanniecluster
/rat/procset file "thermal_neutrons_WbLS_LY095_5.ntuple.root" 
#/rat/procset file "thermal_neutrons_WbLS_LY095_5.ntuple.root" 
/generator/add combo gun:point
/generator/vtx/set neutron 0 0 0 1.0*eV
#/generator/pos/set 0.0 -33.8 1749.4
/generator/pos/set 0.0 0.0 1749.4

/run/beamOn 2000
