/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state true

/rat/db/set DETECTOR experiment "ANNIE" 
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan_sandi.geo" 
/rat/db/load ANNIE/SANDI2_WbLS_Vessel.geo


/run/initialize
#/rat/physics/scintillation/meanPhotonsPerSecondary 1
/rat/proc splitevdaq
/rat/proclast outanniecluster
/rat/procset file "SANDI2_AmBe_LY095.ntuple.root" 
#/rat/procset file "ANNIE_AmBe_AbsWater2016_1.00xQE_0.8xR.ntuple.root" 
/generator/add combo spectrum:point
/generator/vtx/set neutron ambe_test
#/generator/pos/set 0.0 -33.8 1749.4
/generator/pos/set 0.0 466.2 1749.4

/run/beamOn 2
